### ISSUE TITLE
Not working with error reporting middlewares.

### ISSUE THREAD

**Issue by imyelo** [pinojs/koa-pino-logger#10]
The errors passed to these error reporting middlewares will be caught, and then Koa will not calling ``context.onerror``:

- [koa-error](https://github.com/koajs/error/)
- [koa-json-error](https://github.com/koajs/json-error)
- [Some other error reporting middlewares](https://github.com/koajs/koa/wiki#error-reporting)

Maybe overriding `onerror` isn't a good idea I think?

**Comment by davidmarkclements** [comment]
closed by #11
