### ISSUE TITLE
Calling logger from pino()

### ISSUE THREAD

**Issue by wwicaksono** [pinojs/koa-pino-logger#12]
Im using koa-pino-logger 2.1.3 along with koa 2.5.2.

In server.js I made code like this:

```
import Koa from 'koa';
import pinoLogger from './library/logger';

const app = new Koa();
app.use(pinoLogger);

app.listen(port, () => {
  pinoLogger.info(`koa-apis run on port: ${port}`);
});
```

and in library/logger.js I made code like this

```
import logger from 'koa-pino-logger';

const pinoLogger = logger({
  // prettyPrint: true,
  // extreme: true,
  level: 'debug',
});

export default pinoLogger;
```

And it said that pinoLogger.info is not a function.
How can i just call pinoLogger.info or pinoLogger.anyfunctionthatIneed anywhere just like usual pino?

Thanks in advance

**Comment by cutejs** [comment]
The underlying Pino logger is attached to the middleware as `logger`. So to manually log, you'd need to use `pinoLogger.logger.info('blah')`.
