### ISSUE TITLE
`colorize` option doesn't work

### ISSUE THREAD

**Issue by avetisk** [pinojs/koa-pino-logger#16]
## Versions:
```json
{
  "koa": "^2.7.0",
  "koa-pino-logger": "^2.1.3",
  "pino": "^5.11.1",
  "pino-pretty": "^2.5.0"
}
```

## Code
```js
import pinoLogger from 'koa-pino-logger'
// ...
app.use(pinoLogger({
  prettyPrint: {
    colorize: true,
  },
})
// ...
```

## Result
Output has prettified format, but no colors 😢

**Comment by Kresten** [comment]
I don't know if it's because I'm inside a docker, but I have to write `prettyPrint: { forceColor: true }` and then I have colors in my output :). 

BUT when using TypeScript, this will throw a typing error as it is not included as a "PrettyOption", so I have to cast my options to any :(

**Comment by avetisk** [comment]
Yes! Did the same and it worked :)
