### ISSUE TITLE
Update http-pino dependency

### ISSUE THREAD

**Issue by ZackKnopp** [pinojs/koa-pino-logger#17]
Dependency is still `"pino-http": "^2.0.1"`

Need to install updated dependencies myself to use redact. There is already a pull request for this, so I'm just trying to bring visibility to the problem.

**Comment by Lastin** [comment]
Still not working...

**Comment by yorch** [comment]
Same boat.. @davidmarkclements maybe you are looking for help maintaining this project? happy to be involved

**Comment by jmealo** [comment]
@davidmarkclements: #30

**Comment by jmealo** [comment]
> Dependency is still `"pino-http": "^2.0.1"`
> 
> Need to install updated dependencies myself to use redact. There is already a pull request for this, so I'm just trying to bring visibility to the problem.

@ZackKnopp the version has been bumped to latest. Can we close this issue?

**Comment by zacksentrexwind** [comment]
@jmealo Of course :)
