### ISSUE TITLE
Child loggers

### ISSUE THREAD

**Issue by kaboing** [pinojs/koa-pino-logger#18]
What's the proper way to append a child logger? I'd like to append a trace id to all requests, using ctx.state to carry it. 
Somehow do this:
`app.use(correlationIdMiddleware)`
`app.use((ctx) => {`
`  logger({`
`   level: 'debug',`
`   name: 'askas-facade'`
`  }).logger.child({correlationId: ctx.state.correlationId })`
`  }`
`)`

**Comment by kaboing** [comment]
Never mind, I solved it with a middleware added before the logger:
```
const uuid = require('uuid/v4')
const validate = require('uuid-validate')

const correlationIdMiddleware = async (ctx, next) => {
  const requestCorrelationId = ctx.request.header['x-correlation-id']
  const correlationId = validate(requestCorrelationId)
    ? requestCorrelationId
    : uuid()

  ctx.reg.id = correlationId
  ctx.set('X-Correlation-ID', correlationId)

  await next()
}

module.exports = correlationIdMiddleware
```

**Comment by posquit0** [comment]
You can check out this alternative [koa-logging](https://github.com/kasa-network/koa-logging).
