### ISSUE TITLE
Updating for v9

### ISSUE THREAD

**Issue by Ranieri93** [pinojs/koa-pino-logger#63]
Hello everyone!
Following the order on [issue #1762](https://github.com/pinojs/pino/issues/1762) I would like to work on the update for v9.

A few general considerations:
- NPM stats display a total of 1.2 million downloads in the last year
- The last commit dates back to August last year
- It has a direct dependency with [pino-http](https://github.com/pinojs/pino-http)

My evaluation would be to keep this updated because, despite not being that active, the download numbers seem consistent.

I'll wait for your opinion before creating a PR.
@jsumners @mcollina 

Thank you so much in advance for your time!

**Comment by jsumners** [comment]
If this depends on `pino-http`, are you up for getting it ready as well?

**Comment by Ranieri93** [comment]
> If this depends on `pino-http`, are you up for getting it ready as well?

Yeah, sure!
Do you recommend updating that first? It will probably make sense as I guess some of the other libraries will depend on it

**Comment by jsumners** [comment]
Yeah, I think that would be the correct approach. Given that these modules are in use by the ecosystem, we'll have to prepare them on `next` branches and reference the new dependency in this module via a git URL.

Please open an equivalent issue to this one on `pino-http` and I'll get things going.

**Comment by Ranieri93** [comment]
Hey @jsumners, since [this](https://github.com/pinojs/koa-pino-logger/pull/65) has already been merged, I think this issue could be considered done

**Comment by jsumners** [comment]
I see. Thank you for the work and bringing this to my attention.
